Feature image viewer
R2D2-2018/OBJECT_RECOGNITION pull request #7
Opened 2018-05-26 15:08 UTC by Dylrak

This pull request contains the Object Recognition module with all functionality as described by Vertical Slice 1. It also edits some CMake files so that the test.sh script works correctly. The doxygen comments are factored as per the Wiki guidelines. All tests have been written to show off that input is fully validated before utilising it.

2018-05-27 15:47 UTC, wvanbreukelen reviewed
It's very difficult to review this PR. What are the differences between the PR created by Arsalan and yours? Please contact me.

@wvanbreukelen There are differences. Dylan uses code in my library in his main. Everything besides his main is relevant

2018-05-27 15:47 UTC, wvanbreukelen commented on src/image/image.hpp
> +/**
File already reviewed by Arsalan's PR.

2018-06-04 09:11 UTC, JulianvDoorn requested changes

2018-06-04 09:11 UTC, JulianvDoorn commented on .fetch-build-environment.sh
> +git clone ${github_URL} $1
Add `--recursive` to back

2018-06-04 09:11 UTC, JulianvDoorn commented on .gitignore
> +./.clang-format
`.clang-format` and `.clang-format.compare.py` should not be in .gitignore

2018-06-04 09:11 UTC, JulianvDoorn commented on .travis.yml
> +  - cmake CMakeLists.txt
Cmake and make should not be called twice

2018-06-04 09:11 UTC, JulianvDoorn commented on .travis.yml
> +  - make
Cmake and make should not be called twice

2018-06-04 09:11 UTC, JulianvDoorn commented on src/external/libraries/open_cv_types.hpp
>  #include "../../image/sample_image.hpp"
Relative includes are ugly, it would be nice to find a workaround (add `include_directory(src/)` in Sources.cmake?)

2018-06-04 09:11 UTC, JulianvDoorn commented on src/external/libraries/open_cv_types.hpp
> +struct FoundImageData {
Not documented with Doxygen

2018-06-04 09:11 UTC, JulianvDoorn commented on src/external/libraries/open_cv_types.hpp
> +typedef struct {
Not documented with Doxygen

typedef struct is C style struct declarations. Use classes

2018-06-04 09:11 UTC, JulianvDoorn commented on src/external/libraries/open_cv_types.hpp
> +struct FoundImageData {
Use classes

2018-06-04 09:11 UTC, JulianvDoorn commented on src/external/libraries/open_cv_types.hpp
> +typedef std::vector<cv::KeyPoint> FeatureList;
Typedef should be 
`using FeatureList = std::vector<cv::KeyPoint>;`

2018-06-04 09:11 UTC, JulianvDoorn commented on src/external/settings.hpp
> +struct data {
Not documented with Doxygen

Use class

2018-06-04 09:11 UTC, JulianvDoorn commented on src/external/settings.hpp
> +struct data {
Not documented with Doxygen

Use class

2018-06-04 09:11 UTC, JulianvDoorn commented on src/external/settings.hpp
> +struct data {
Not documented with Doxygen

Use class

2018-06-04 09:11 UTC, JulianvDoorn commented on src/external/settings.hpp
> +struct data {
Not documented with Doxygen

Use class

2018-06-04 09:11 UTC, JulianvDoorn commented on src/external/settings.hpp
> +struct data {
Not documented with Doxygen

Use class

2018-06-04 09:11 UTC, JulianvDoorn commented on src/external/types.hpp
> +struct WindowSize {
Not documented with Doxygen

Use class

2018-06-04 09:11 UTC, JulianvDoorn commented on src/image/root_image.cpp
> +    if (!image.data) /// Check for invalid input
Inconsistent bracket placement, it seems to be common that the bracket should be on the same line as the if statement

2018-06-04 09:11 UTC, JulianvDoorn commented on src/image/sample_image.cpp
> +SampleImage::SampleImage() {
It is advised to set all internal pointers to nullptr in default constructor

2018-06-04 09:11 UTC, JulianvDoorn commented on src/image/sample_image.hpp
> +    SampleImage(const char *path, settings::IMG::data &settings);
Doxygen for constructor missing

2018-06-04 09:11 UTC, JulianvDoorn commented on src/image/root_image.hpp
> +    RootImage(const char *path, settings::IMG::data &settings);
Doxygen for constructor missing

2018-06-04 09:11 UTC, JulianvDoorn commented on src/image/sample_image.hpp
>  typedef std::vector<SampleImage> SampleImageList;
`using SampleImageList = std::vector<SampleImage>`

2018-06-04 09:11 UTC, JulianvDoorn commented on src/object_finding/feature_comparator.hpp
>  #include "../image/root_image.hpp"
Relative include is disadvised

2018-06-04 09:11 UTC, JulianvDoorn commented on src/object_finding/feature_comparator.hpp
> +    FeatureComparator(lucidy::settings::OBF::data &settings);
Doxygen missing constructor

2018-06-04 09:11 UTC, JulianvDoorn commented on src/object_finding/feature_descriptor.hpp
> +    FeatureDescriptor(FeatureDetector &detector, settings::FDC::data &settings);
Doxygen missing constructor

2018-06-04 09:11 UTC, JulianvDoorn commented on src/object_finding/feature_detector.hpp
> +#include "../external/settings.hpp"
Relative include is disadvised

2018-06-04 09:11 UTC, JulianvDoorn commented on src/object_finding/feature_detector.hpp
> +    FeatureDetector(settings::FDT::data &settings);
Doxygen missing for constructor

2018-06-04 09:11 UTC, JulianvDoorn commented on src/object_finding/object_finder.hpp
> +    ObjectFinder(settings::OBF::data &settings);
Doxygen missing constructor

2018-06-04 09:11 UTC, JulianvDoorn commented on src/test_log/image_parser_viewer.cpp
> +// #define CATCH_CONFIG_MAIN
Commented file may not be merged into development

2018-06-04 09:11 UTC, JulianvDoorn commented on src/test_log/template_code.cpp
> +// #include <iostream>
Commented file may not be merged into development

2018-06-04 09:11 UTC, JulianvDoorn commented on src/window/image_viewer.hpp
> +#include "../image/image.hpp"
Relative include is disadvised

2018-06-04 09:11 UTC, JulianvDoorn commented on src/window/image_viewer.hpp
> +    ImageViewer(settings::WIN::GUI::data &settings);
Doxygen missing constructors

2018-06-04 09:11 UTC, JulianvDoorn commented on src/window/interface/window.hpp
> +#include "../../external/settings.hpp"
Relative include is disadvised

2018-06-04 09:11 UTC, JulianvDoorn commented on test/test_main.cpp
> +#include "../src/external/settings.hpp"
Relative include is disadvised

2018-06-04 09:11 UTC, JulianvDoorn commented on test/test_main.cpp
> +// TEST_CASE("SampleImage user input parser ", "UserInput Test"){
Commented test case may not be merged

2018-06-04 09:11 UTC, JulianvDoorn commented on test/test_main.cpp
> +// TEST_CASE("RootImage user input parser ", "UserInput Test"){
Commented test case may not be merged

2018-06-18 07:39 UTC, Qperquin commented
Closing pull request: Irrelevant for current situation.

2018-06-18 07:39 UTC, closed without merging